# Generated by Django 4.2.3 on 2023-10-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_blog_alter_comments_content_delete_contents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
